name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build

      - name: Transfer files to server
        uses: appleboy/scp-action@v0.0.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist/**, package.json, package-lock.json"
          target: "/usr/share/nginx/ecom-backend"

      - name: Install dependencies on server
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /usr/share/nginx/ecom-backend && npm install --force'

      - name: Restart application
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'pm2 restart esale-api || pm2 start esale-api' 
